import { Color3 } from '@babylonjs/core';

export const SKY_CONFIG = {
  skyRadius: 1000,
  horizonRadius: 980,
  defaultMagnitudeLimit: 5.8,
  nakedEyeMagnitudeLimit: 6.0,
  starLabelMagnitudeLimit: 2.2,
  planetLabelMagnitudeLimit: 6.5,
  realtimeUpdateMs: 5000,
  clockUpdateMs: 1000,
  sensorUpdateMs: 50,
  sensorSmoothingFactor: 0.18,
  defaultAlignmentMode: 'demo',
  defaultTimeMode: 'realtime',
  defaultLocation: {
    latitude: 16.5062,
    longitude: 80.6480,
    label: 'Demo Location',
    source: 'default',
  },
  showBelowHorizonDefault: false,
  showConstellationsDefault: false,
  showLabelsDefault: true,
  showHorizonDefault: true,
  showSunDefault: true,
  showMoonDefault: true,
  showPlanetsDefault: true,
  showStarsDefault: true,
  qualityDefault: 'medium',
};

// Visibility depends on sky brightness, clouds, pollution, terrain, twilight, and eyesight.
// Uranus and Neptune are included for completeness but usually require optical aid.
export const SKY_BODIES = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'sun',
    displayColor: new Color3(1, 0.82, 0.22),
    labelPriority: 1,
    nakedEyeNote: 'Visible in daytime when above the horizon, but never safe to stare at.',
    learningFact: 'The Sun is our nearest star and the main source of energy for Earth.',
    safetyNote: 'Never look directly at the real Sun, especially through binoculars or telescopes.',
  },
  {
    id: 'moon',
    name: 'Moon',
    type: 'moon',
    displayColor: new Color3(0.82, 0.84, 0.78),
    labelPriority: 1,
    nakedEyeNote: 'Often easy to see when above the horizon, depending on phase and daylight.',
    learningFact: 'The Moon reflects sunlight and changes phase as it orbits Earth.',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    displayColor: new Color3(0.68, 0.63, 0.54),
    labelPriority: 4,
    nakedEyeNote: 'Can be visible near twilight, low toward the horizon.',
    learningFact: 'Mercury stays close to the Sun in our sky because it orbits inside Earth.',
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    displayColor: new Color3(1, 0.86, 0.56),
    labelPriority: 2,
    nakedEyeNote: 'Often one of the brightest planet-like objects when above the horizon.',
    learningFact: 'Venus is covered by bright clouds and can appear as the Morning or Evening Star.',
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    displayColor: new Color3(1, 0.34, 0.18),
    labelPriority: 3,
    nakedEyeNote: 'Visible to the naked eye when bright enough and well placed.',
    learningFact: 'Mars often looks reddish because of iron-rich dust on its surface.',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    displayColor: new Color3(1, 0.72, 0.42),
    labelPriority: 1,
    nakedEyeNote: 'Often very bright and easy to spot when above the horizon.',
    learningFact: 'Jupiter is the largest planet in the Solar System and is often one of the brightest planet-like objects in the night sky.',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    displayColor: new Color3(1, 0.82, 0.52),
    labelPriority: 2,
    nakedEyeNote: 'Usually visible as a steady yellowish point when well placed.',
    learningFact: 'Saturn is famous for its rings, which need a telescope to see clearly.',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    displayColor: new Color3(0.48, 0.9, 0.95),
    labelPriority: 6,
    nakedEyeNote: 'Usually requires binoculars or a very dark sky.',
    learningFact: 'Uranus is an ice giant with an extreme axial tilt.',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    displayColor: new Color3(0.25, 0.45, 1),
    labelPriority: 6,
    nakedEyeNote: 'Requires optical aid for normal observers.',
    learningFact: 'Neptune is a distant ice giant with very fast winds.',
  },
];
